plugins {
    id 'fabric-loom' version '1.14-SNAPSHOT'
    id 'maven-publish'
}

version = "1.6.0-mc1.21.8"
group = 'com.example'

base {
    archivesName = "throwallmoveall"
}

repositories {
    mavenCentral()
    maven { url = uri('https://maven.fabricmc.net/') }
    maven { url = uri('https://maven.terraformersmc.com/releases/') }
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
        }
        resources {
            srcDirs = [
                rootProject.file('common/src/main/resources'),
                'src/main/resources'
            ]
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.8"
    mappings "net.fabricmc:yarn:1.21.8+build.1:v2"
    modImplementation "net.fabricmc:fabric-loader:0.16.10"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.132.0+1.21.8"
    modCompileOnly "com.terraformersmc:modmenu:14.0.0"
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
